services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coworking_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: user.cuscatlan
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: