spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coworking_db
    username: root
    password: user.cuscatlan

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true